### ISSUE TITLE
Automate CI/CD for the example Rails app

### ISSUE THREAD

**Issue by bilus** [bilus/oya#16]
## Acceptance criteria

1. Use CircleCI
2. Use Heroku
3. On push to branch, run tests.
4. On merge to master, deploy to Heroku.
5. Pack for heroku: `deploy`.
6. Pack for CircleCI: 
- `generate` -> to modify Oyafile & generate .circle/config.yml & show help

```
Project:
Import:
  heroku: github.com/tooploox/packs/heroku
  ci: github..

onPush: |
  rake test

onMergeToMaster: |
  oya run heroku.deploy production $Values.projectName
```
