### ISSUE TITLE
Ask user for overrides for defaults

### ISSUE THREAD

**Issue by bilus** [bilus/oya#3]
## Acceptance criteria

1. Option to overwrite defaults in pack's Values.
2. Ask user:

```
Port to expose the app on (default: 8000): _____
[...]
```

## Proposal

`github.com/bart84ek/oya-packs/docker/Oyafile`

```yaml
Values: 
   port: 8000
   

Ask:
  port: "Port to expose the app on"
```
