### ISSUE TITLE
Automate update Oyafile after circleCI generate.

### ISSUE THREAD

**Issue by pabielicki** [bilus/oya#31]
```
Project:
Import:
  heroku: github.com/tooploox/packs/heroku
  ci: github..

onPush: |
  rake test

onMergeToMaster: |
  oya run heroku.deploy production $Values.projectName
```
